// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHRBWjh-FwKfLlzRFSFVPDtkXq7mvY2z0',
    appId: '1:1054326201764:android:9fa01b638600f65b5b7531',
    messagingSenderId: '1054326201764',
    projectId: 'qrquiz',
    storageBucket: 'qrquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyguFnJQas7PtSPXl5VYIt-mutI-f1Oz0',
    appId: '1:1054326201764:ios:98be17743d9db8645b7531',
    messagingSenderId: '1054326201764',
    projectId: 'qrquiz',
    storageBucket: 'qrquiz.appspot.com',
    iosClientId: '1054326201764-t5m18msqgi1akhb3nlp9c8t00dse7ri7.apps.googleusercontent.com',
    iosBundleId: 'com.app.qrquiz',
  );
}
